export {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
  type CardProps,
  type CardHeaderProps,
  type CardTitleProps,
  type CardDescriptionProps,
  type CardContentProps,
  type CardFooterProps,
  type CardVariant,
  type CardPadding,
  type CardHover,
} from "./Card";
export {
  cardStyles,
  cardTitleStyles,
  cardDescriptionStyles,
  cardVariants,
  cardPaddings,
  cardHoverStyles,
  type CardStyleProps,
  type CardTitleStyleProps,
  type CardDescriptionStyleProps,
} from "./Card.styles";
